controller_list:
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - f_joint1
      - f_joint2
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_mobile_controller
    type: $(arg fake_execution_type)
    joints:
      - back_left_caster_hinge
      - back_right_caster_hinge
      - front_left_caster_hinge
      - front_right_caster_hinge
      - left_wheel_hinge
      - right_wheel_hinge
initial:  # Define initial robot poses per group
  - group: gripper
    pose: open_grip
  - group: arm
    pose: init_arm