controller_list:
  - name: arm_controller_follow
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: gripper_controller_follow
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - f_joint1
      - f_joint2
  - name: mobile_controller_follow
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_left_caster_hinge
      - back_right_caster_hinge
      - front_left_caster_hinge
      - front_right_caster_hinge
      - left_wheel_hinge
      - right_wheel_hinge
  - name: arm_controller_position
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: gripper_controller_effort
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - f_joint1
      - f_joint2
  - name: mobile_controller_position
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_left_caster_hinge
      - back_right_caster_hinge
      - front_left_caster_hinge
      - front_right_caster_hinge
      - left_wheel_hinge
      - right_wheel_hinge
  - name: mobile_controller_velocity
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - back_left_caster_hinge
      - back_right_caster_hinge
      - front_left_caster_hinge
      - front_right_caster_hinge
      - left_wheel_hinge
      - right_wheel_hinge