controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_grip_controller
    type: $(arg fake_execution_type)
    joints:
      - f_joint1
      - f_joint2
  - name: fake_mobile_controller
    type: $(arg fake_execution_type)
    joints:
      - left_wheel_hinge
      - right_wheel_hinge
initial:  # Define initial robot poses per group
  - group: arm
    pose: init
  - group: grip
    pose: open