mixed_robot:
  controller_list:
    - name: fake_gripper_controller
      type: $(arg fake_execution_type)
      joints:
        - f_joint1
        - f_joint2
    - name: fake_arm_controller
      type: $(arg fake_execution_type)
      joints:
        - joint1
        - joint2
        - joint3
        - joint4
        - joint5
        - joint6
    - name: fake_mobile_controller
      type: $(arg fake_execution_type)
      joints:
        - left_wheel_hinge
        - right_wheel_hinge
    - name: fake_footprint_group_controller
      type: $(arg fake_execution_type)
      joints:
        []
  initial:  # Define initial robot poses per group
    - group: gripper
      pose: open
    - group: arm
      pose: init