# Publish joint_states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
diff_drive_controller:
   type: diff_drive_controller/DiffDriveController
   publish_rate: 50   
