controller_list:
  - name: gripper_controller_effort
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - f_joint1
      - f_joint2
  - name: arm_controller_pos
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: mobile_controller_velocity
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_wheel_hinge
      - right_wheel_hinge
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - f_joint1
      - f_joint2
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: mobile_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_wheel_hinge
      - right_wheel_hinge

